//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Apexia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDay
    {
        public int WorkDayID { get; set; }
        public string Checkin { get; set; }
        public string Checkout { get; set; }
        public string Breaks { get; set; }
        public string Lunch { get; set; }
        public Nullable<int> TotalHoursWorked { get; set; }
        public Nullable<int> OvetimeHours { get; set; }
        public string Comments { get; set; }
        public string Date { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
