//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Apexia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int WorkScheduleID { get; set; }
        public string WeekendDays { get; set; }
        public Nullable<int> HoursPerDay { get; set; }
        public string WeekStarts { get; set; }
        public Nullable<int> NumberWorkDays { get; set; }
        public string DayStarts { get; set; }
        public string Breaks { get; set; }
        public string Lunch { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
    }
}
