//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexiaHR_Pfe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSetting
    {
        public string Attendance { get; set; }
        public string EmployeeBreak { get; set; }
        public string WeekendOnAttendanceSheet { get; set; }
        public string MaxLateArrivals { get; set; }
        public string HighlightLateArrivals { get; set; }
        public Nullable<Guid> CompanyID { get; set; }
        public int TimeSettingID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
